### ISSUE TITLE
Is it supports the GraphSONMessageSerializerV3d0?

### ISSUE THREAD

**Issue by tibraga** [jbmusso/gremlin-javascript#100]
Look my cenarius:

The tinerkpop server conf (serializer)
```
- { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { useMapperFromGraph: graph }}
- { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV2d0, config: { useMapperFromGraph: graph }}
- { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { useMapperFromGraph: graph }}
```

Before run the code below, In the console tinkerpop, I added one vertex: `g.add('test')`

When I run this code:

```
gremlin = require('gremlin');
const client = gremlin.createClient(8182, "localhost", { accept: "application/vnd.gremlin-v2.0+json" });
client.execute('g.V().limit(2)', (err, results) => {
      if (err) {
          return console.error(err)
      }
      console.log(results);
});
```

It's works. But when changes the option of client (accept) from `application/vnd.gremlin-v2.0+json` to `application/json`, happens the below error:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Expected Stream, got object
    at /Users/tiago.machado/temp/node_modules/highland/lib/index.js:3504:26
    at /Users/tiago.machado/temp/node_modules/highland/lib/index.js:1576:9
    at Stream.s._send (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:959:26)
    at push (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:1498:19)
    at /Users/tiago.machado/temp/node_modules/highland/lib/index.js:2104:13
    at Stream.s._send (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:1532:9)
    at Stream.write (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:1633:18)
    at Stream._send (/Users/tiago.machado/temp/node_modules/highland/lib/index.js:959:26)
```

Is the client supports the GraphSONMessageSerializerV3d0?

Thanks!

**Comment by Tomen** [comment]
Duplicate of #91
