### ISSUE TITLE
serialization error

### ISSUE THREAD

**Issue by oren** [jbmusso/gremlin-javascript#15]
```
var gremlin = require('gremlin-client');
var client = gremlin.createClient(8182, 'localhost');

var query = client.stream('g.addV("bela", "menere")');

query.on('data', function(result) {
  console.log('result', result);
});

query.on('end', function() {
  console.log("All results fetched");
});
```

script output:
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Error: Error during serialization: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"]) (Error 599)
    at MessageStream.<anonymous> (/home/oren/projects/titan/titan-test/node_modules/gremlin-client/src/gremlinclient.js:264:26)
    at emitOne (events.js:77:13)
    at MessageStream.emit (events.js:169:7)
    at GremlinClient.handleMessage (/home/oren/projects/titan/titan-test/node_modules/gremlin-client/src/gremlinclient.js:83:21)
    at WebSocket.onMessage (/home/oren/projects/titan/titan-test/node_modules/gremlin-client/node_modules/ws/lib/WebSocket.js:414:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/oren/projects/titan/titan-test/node_modules/gremlin-client/node_modules/ws/lib/WebSocket.js:797:10)
    at /home/oren/projects/titan/titan-test/node_modules/gremlin-client/node_modules/ws/lib/Receiver.js:473:18
    at Receiver.applyExtensions (/home/oren/projects/titan/titan-test/node_modules/gremlin-client/node_modules/ws/lib/Receiver.js:360:5)
```

server log:
```
titan_1         | 552629 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0  - Response [ResponseMessage{requestId=85e14a97-7bb7-4727-5ecb-50cde02ae446, status=ResponseStatus{code=SUCCESS, message='', attributes={}}, result=ResponseResult{data=[v[4216]], meta={}}}] could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0.
titan_1         | 552631 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder  - The result [ResponseResult{data=[v[4216]], meta={}}] in the request 85e14a97-7bb7-4727-5ecb-50cde02ae446 could not be serialized and returned.
titan_1         | org.apache.tinkerpop.gremlin.driver.ser.SerializationException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
titan_1         |       at org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0.serializeResponseAsString(GraphSONMessageSerializerV1d0.java:101)
titan_1         |       at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:79)
titan_1         |       at org.apache.tinkerpop.gremlin.server.handler.WsGremlinResponseEncoder.encode(WsGremlinResponseEncoder.java:45)
titan_1         |       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
titan_1         |       at org.apache.tinkerpop.gremlin.server.handler.IteratorHandler.write(IteratorHandler.java:119)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:32)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:908)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:960)
titan_1         |       at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:893)
titan_1         |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
titan_1         |       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
titan_1         |       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
titan_1         |       at java.lang.Thread.run(Thread.java:745)
titan_1         | Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdentifier["inVertexId"])
titan_1         |       at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
titan_1         |       at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
titan_1         |       at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:186)
titan_1         |       at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:640)
titan_1         |       at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:49)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.serializerVertexProperty(GraphSONSerializers.java:336)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers.access$000(GraphSONSerializers.java:55)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexJacksonSerializer.writeProperties(GraphSONSerializers.java:216)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexJacksonSerializer.ser(GraphSONSerializers.java:193)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexJacksonSerializer.serialize(GraphSONSerializers.java:175)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONSerializers$VertexJacksonSerializer.serialize(GraphSONSerializers.java:163)
titan_1         |       at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:100)
titan_1         |       at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:21)
titan_1         |       at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:183)
titan_1         |       at org.apache.tinkerpop.gremlin.structure.io.graphson.GraphSONUtil.writeWithType(GraphSONUtil.java:49)
titan_1         |       at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0$ResponseMessageSerializer.ser(AbstractGraphSONMessageSerializerV1d0.java:235)
titan_1         |       at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractGraphSONMessageSerializerV1d
0.java:205)
titan_1         |       at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV1d0$ResponseMessageSerializer.serialize(AbstractGraphSONMessageSerializerV1d0.java:197)
titan_1         |       at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
titan_1         |       at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2811)
titan_1         |       at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2268)
titan_1         |       at org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0.serializeResponseAsString(GraphSONMessageSerializerV1d0.java:98)
titan_1         |       ... 16 more
titan_1         | Caused by: java.lang.IllegalStateException
titan_1         |       at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
titan_1         |       at com.thinkaurelius.titan.graphdb.relations.RelationIdentifier.getInVertexId(RelationIdentifier.java:69)
titan_1         |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
titan_1         |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
titan_1         |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
titan_1         |       at java.lang.reflect.Method.invoke(Method.java:497)
titan_1         |       at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.get(BeanPropertyWriter.java:726)
titan_1         |       at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:506)
titan_1         |       at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:632)
titan_1         |       ... 35 more
cassandra_1     |  INFO 08:02:26,143 Enqueuing flush of Memtable-batchlog@934169300(513/5130 serialized/live bytes, 12 ops)
cassandra_1     |  INFO 08:02:26,145 Writing Memtable-batchlog@934169300(513/5130 serialized/live bytes, 12 ops)
cassandra_1     |  INFO 08:02:26,149 Completed flushing; nothing needed to be retained.  Commitlog position was ReplayPosition(segmentId=1441698771246, position=157250)
```

According to https://github.com/phani1kumar/docker-titan/issues/4#issuecomment-138777474 there should be a way to pass serialization to the gremlin-client. any ideas how it is being done?

**Comment by oren** [comment]
I am closing this since I was able to run it successfully again titan 1.0.0 and without docker. if i'll ever try to use the dockerized approach, i'll update this issue.

**Comment by jlabarbera11** [comment]
I'm running into the same issue, getting the following error when trying to add a vertex:

`> Error: Error during serialization: (was java.lang.IllegalStateException) (through reference chain: java.util.ArrayList[0]->com.thinkaurelius.titan.graphdb.relations.RelationIdenti
fier["inVertexId"]) (Error 599)
    at GremlinClient.handleProtocolMessage (/Users/joe/titan/titan/node_modules/gremlin/lib/GremlinClient.js:174:39)
    at WebSocketGremlinConnection.<anonymous> (/Users/joe/titan/titan/node_modules/gremlin/lib/GremlinClient.js:120:23)
    at emitOne (events.js:96:13)
    at WebSocketGremlinConnection.emit (events.js:188:7)
    at WebSocketGremlinConnection.handleMessage (/Users/joe/titan/titan/node_modules/gremlin/lib/WebSocketGremlinConnection.js:69:12)
    at WebSocketGremlinConnection._this.ws.onmessage (/Users/joe/titan/titan/node_modules/gremlin/lib/WebSocketGremlinConnection.js:46:20)
    at WebSocket.onMessage (/Users/joe/titan/titan/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)`


This is what my gremlin-server.yaml looks like:

`host: 0.0.0.0
port: 8182
threadPoolWorker: 1
gremlinPool: 8
scriptEvaluationTimeout: 30000
serializedResponseTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphs: {
  graph: conf/gremlin-server/titan-cassandra-es-server.properties}
plugins:
  - aurelius.titan
scriptEngines: {
  gremlin-groovy: {
    imports: [java.lang.Math],
    staticImports: [java.lang.Math.PI],
    scripts: [scripts/empty-sample.groovy]},
  nashorn: {
      imports: [java.lang.Math],
      staticImports: [java.lang.Math.PI]}}
serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { useMapperFromGraph: graph }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GryoMessageSerializerV1d0, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0 }
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0 }
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 }}
metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
threadPoolBoss: 1
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferHighWaterMark: 32768
writeBufferHighWaterMark: 65536
ssl: {
  enabled: false}`

**Comment by jbmusso** [comment]
@jlabarbera11 Thanks for sharing this. Which version of the client do you use?

**Comment by PommeVerte** [comment]
FYI in general this can happen because of a missing graph mapper configuration : 
```yaml
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV1d0, config: { useMapperFromGraph: graph }}
```

**Comment by jlabarbera11** [comment]
I'm using version 2.3.2, but adding the above configuration solved my issue. Thanks!

**Comment by jbmusso** [comment]
Cool - glad you managed your wait out!
