### ISSUE TITLE
g.addV doesn't work with the binding argument

### ISSUE THREAD

**Issue by oren** [jbmusso/gremlin-javascript#16]
Insert without the binding argument works:
``` js
var script = 'g.addV("name", "kelly")';
var query = client.stream(script);
```

But with the binding argument I get an error:
``` js
var script = 'g.addV(name)'
var bindings = {name: 'kelly'};
var query = client.stream(script, bindings);
```

```events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: The provided key/value array length must be a multiple of two (Error 500)
    at MessageStream.<anonymous> (/home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/src/gremlinclient.js:264:26)
    at emitOne (events.js:77:13)
    at MessageStream.emit (events.js:169:7)
    at GremlinClient.handleMessage (/home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/src/gremlinclient.js:83:21)
    at WebSocket.onMessage (/home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/node_modules/ws/lib/Receiver.js:477:18
    at Receiver.applyExtensions (/home/oren/projects/titan/titan-gremlin-client/node_modules/gremlin-client/node_modules/ws/lib/Receiver.js:364:5)
```

**Comment by jbmusso** [comment]
You're dealing with a server side error.

In TinkerPop3, `addV()` [expects an even number of arguments](http://tinkerpop.incubator.apache.org/docs/3.0.0-incubating/#addvertex-step). Optionally, the first pair of key/value can be used to create a labeled vertex, ie: `g.addV(label, 'human', 'name', 'kelly')`.

By sending `g.addV(name)` to Gremlin Server, you're only calling `addV()` with one argument. Gremlin-Javascript doesn't handle passing objects mapped as `key, value` pairs from JavaScript object literals. You should try the following:

```javascript
var script = 'g.addV(key, value)';
var bindings = { key: 'name', value: 'kelly' };
var query = client.stream(script, bindings);
```

However, you might likely just want to do this:
```javascript
var script = 'g.addV("name", name)';
var bindings = { name: 'kelly' };
var query = client.stream(script, bindings);
```
Let me know how it goes.
