### ISSUE TITLE
No compatible version found: left-pad@0.0.3

### ISSUE THREAD

**Issue by guyellis** [jbmusso/gremlin-javascript#38]
Doing an `npm i` on this project I got:

```
guy@MSI-GS60:~/source/gremlin-javascript$ npm i
npm WARN deprecated karma-browserify@0.2.1: Full rewrite in 1.0. 0.x is deprecated.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 3.16.0-67-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 0.0.9
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/guy/source/gremlin-javascript/npm-debug.log
```

The pertinent info from the npm-debug.log is:

```
12013 verbose stack Error: No compatible version found: left-pad@0.0.3
12013 verbose stack Valid install targets:
12013 verbose stack 0.0.9
12013 verbose stack
12013 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
12013 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
12013 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
12013 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
12013 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
12013 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
12014 verbose cwd /home/guy/source/gremlin-javascript
```

I'm guessing this is a Mac vs Linux thing?

My OS:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

**Comment by PommeVerte** [comment]
This is very recent. The maintainers of `left-pad` have chosen to unpublish it, for reasons that are not yet clear. Unfortunately `babelify` & `gulp-babel`, among others, use left-pad. I'll post a link to an issue in those repos once I find one.

**Comment by guyellis** [comment]
Okay - looks like this is a node wide problem: https://github.com/facebook/react-native/issues/6595

**Comment by PommeVerte** [comment]
https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.vpj0s7qmk
This is going to be fun.

**Comment by PommeVerte** [comment]
In the meantime you should be able to do the following and operate normally :  
```
npm install azer/left-pad.git#bff80e3ef0db0bfaba7698606c4f623433d14355
```
At least until this thing blows over and everyone updates their dependencies.

**Comment by PommeVerte** [comment]
fixed https://twitter.com/seldo/status/712414400808755200

**Comment by jbmusso** [comment]
You can get more information from the author of left-pad here: https://news.ycombinator.com/item?id=11340510

HackerNews: https://news.ycombinator.com/item?id=11340510
