### ISSUE TITLE
Examples aren't working

### ISSUE THREAD

**Issue by guyellis** [jbmusso/gremlin-javascript#40]
When running the examples I get:

```
guy@MSI-GS60:~/source/gremlin-javascript/examples$ node node-example
module.js:341
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/guy/source/gremlin-javascript/examples/node-example.js:1:77)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

I created a PR to discuss this and then realized that I should have created an issue first. So this is that issue. Here is the PR: https://github.com/jbmusso/gremlin-javascript/pull/39

**Comment by PommeVerte** [comment]
Gonna let jb look at this. In the meantime can you tell me which query leads to : 
```
[Error: No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.getAt() is applicable for argument types: (groovy.lang.IntRange) values: [1..2]
Possible solutions: getAt(int), getAt(java.lang.String), next(), reset(), putAt(java.lang.String, java.lang.Object), wait() (Error 597)] undefined
[Error: Error: No signature of method: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.getAt() is applicable for argument types: (groovy.lang.IntRange) values: [1..2]
Possible solutions: getAt(int), getAt(java.lang.String), next(), reset(), putAt(java.lang.String, java.lang.Object), wait() (Error 597)]
```

**Comment by PommeVerte** [comment]
Looking at the code here it looks like these examples date back to TP2. These will need to be rewritten.

**Comment by PommeVerte** [comment]
```groovy
g.V()[1..2] // should be : g.V().range(1, 2)
```
```groovy
g.v(x) // should be : g.V(id) or g.V().has(id, x)
```

**Comment by jbmusso** [comment]
The examples were written while TP3 was still in the early development phase so they are indeed very outdated - sorry about that. I need to be more careful with these now that the library is grabbing some attention. Thanks for sending a PR, I'll try to review it soon (hopefully this evening).

**Comment by guyellis** [comment]
I just made the change that @PommeVerte suggested and that fixes this issue. It's in the PR.

@PommeVerte the query was the `node-example` one.

Question, is this the expected output from `node-example`:

```
null []
All results fetched
```

**Comment by PommeVerte** [comment]
I'm not sure, I would think not. Have you set the database up correctly using the `build/gremlin-server/gremlin-server-js.yaml`file?

**Comment by guyellis** [comment]
> Have you set the database up correctly using the build/gremlin-server/gremlin-server-js.yamlfile?

No I have not. I've just been using the gremlin console with the standard installation so far. New to this so not sure how to do what you just asked.

**Comment by PommeVerte** [comment]
You place that file in the gremlin-server `conf/` folder and start the server with `./bin/gremlin-server.sh conf/gremlin-server-js.yaml

**Comment by guyellis** [comment]
@PommeVerte is this your image? https://hub.docker.com/r/dmillgremlin/gremlin-server/

Will running that image provide the gremlin-server I need?

(I ask because I'm hitting unrelated-to-this-problem-errors when trying to run the gremlin-server off that .yaml file.)

**Comment by PommeVerte** [comment]
Yes that is my image. I wasn't finished with it so it only partially works (also why there's no documentation attached).
Here's how to use it for your use case (remember to fetch it again as I've just made some changes) : 
Create a folder, lets call it `custom-gremlin-server`. In the folder place any files you want to change on the server by following the same folder structure. For example you want to use `gremlin-server-js.yaml`. So place that file at `custom-gremlin-server/conf/gremlin-server.yaml`

Then run the docker container with the following (remember to change the `custom-gremlin-server` path):
```
sudo docker run -d --name testing-gs -v /full/path/to/gremlin-server-custom:/gremlin-server/conf dmillgremlin/gremlin-server:3.1.1
```
- **-d** run as daemon in the background. You can omit this if you want to see the log output
- **--name** the name of the container so you can easily stop / remove it later.
- **-v** mount your local folder into the container
- **dmillgremlin/gremlin-server:3.1.1** use gremlin-server 3.1.1 (3.1.0 also available)

**Comment by guyellis** [comment]
@PommeVerte do you have a sample `gremlin-server.yaml` file that you're putting in that mounted folder?

**Comment by PommeVerte** [comment]
Yeah it's in this repo : https://github.com/jbmusso/gremlin-javascript/blob/master/build/gremlin-server/gremlin-server-js.yaml

With this file (you just need to rename it) it should open the graph with the appropriate content. 

If you don't do the above then it defaults to : https://github.com/apache/incubator-tinkerpop/blob/master/gremlin-server/conf/gremlin-server.yaml

**Comment by PommeVerte** [comment]
Btw you will need to get the container ip to connect to it (if you aren't familiar with docker)

**Comment by guyellis** [comment]
Thanks @PommeVerte 

In case anyone else comes across this, here are some steps to use this with the Docker container:

1. As @PommeVerte mentioned, copy the `gremlin-server-js.yml` file to the folder that you're going to mount with docker and rename it to `gremlin-server.yml`
2. Start the Docker container: `docker run -p 8182:8182 -d --name testing-gs -v /opt/titan/conf/gremlin-server:/gremlin-server/conf dmillgremlin/gremlin-server:3.1.1`
3. Find the IP address of the container: `docker inspect | grep "IPA"`
4. Edit `examples/node-example.js` file and add the port and IP to the `createClient()` command. e.g.: `var client = gremlin.createClient('8182', '127.0.0.2');`
5. Run the example: `npm run examples:node` (assumes that PR #39 has been merged)

Result:

```
$ npm run examples:node

> gremlin@2.2.0 examples:node /home/guy/source/gremlin-javascript
> babel-node examples/node-example

{ id: 2,
  label: 'vertex',
  type: 'vertex',
  properties: { name: [ [Object] ], age: [ [Object] ] } }
null [ { id: 2,
    label: 'vertex',
    type: 'vertex',
    properties: { name: [Object], age: [Object] } } ]
All results fetched
```
