### ISSUE TITLE
'messageStream' of undefined with titan error 599

### ISSUE THREAD

**Issue by ehouguet** [jbmusso/gremlin-javascript#56]
Here an error to manage.

this error come when titan return an error 599.

Erreur of titan :
[Error: Error during serialization: GC overhead limit exceeded (Error 599)]

Error of gremlin-javascript :
C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\lib\GremlinClient.js:153
      var messageStream = this.commands[requestId].messageStream;
                                                  ^
 
TypeError: Cannot read property 'messageStream' of undefined
    at GremlinClient.handleProtocolMessage (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\lib\Gremli
nClient.js:153:51)
    at WebSocketGremlinConnection.<anonymous> (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\lib\Gre
mlinClient.js:120:23)
    at emitOne (events.js:77:13)
    at WebSocketGremlinConnection.emit (events.js:169:7)
    at WebSocketGremlinConnection.handleMessage (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\lib\W
ebSocketGremlinConnection.js:69:12)
    at WebSocketGremlinConnection._this.ws.onmessage (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\
lib\WebSocketGremlinConnection.js:46:20)
    at WebSocket.onMessage (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\node_modules\ws\lib\WebSoc
ket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\b03614\Documents\my-contacts-ui\app\node_modules\gremlin\node_modules\ws\lib\WebSocke
t.js:823:10)

**Comment by PommeVerte** [comment]
Thanks! Will look into fixing this.

**Comment by jbmusso** [comment]
Thanks for posting this. I can think of a quick fix with the current version. I'm really considering [switching the internal of the lib to Observable/RxJS](https://github.com/jbmusso/gremlin-javascript/tree/rxjs) and I think that bug could be already fixed on that branch.

**Comment by ehouguet** [comment]
thank you !!!
